FROM node:18.18.0-alpine3.17 AS web-app-builder
RUN apk add --no-cache python3
ENV NODE_ENV production
WORKDIR /app
COPY . /app/
EXPOSE 3000
WORKDIR /app/.wasp/build/web-app
#RUN npm ci && REACT_APP_API_URL=$REACT_APP_API_URL npm run build
ENTRYPOINT ["npm", "run", "start-production"]


# Any user-defined Dockerfile contents will be appended below.
FROM joseluisq/static-web-server AS web-app-production
ENV SERVER_PORT=3000
COPY --from=web-app-builder /app/.wasp/build/web-app/build /public


