kind: Deployment
apiVersion: apps/v1
metadata:
  name: wasp-dev-db
  namespace: my-super-saas
  labels:
    app: wasp-dev-db-opensaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasp-dev-db
  template:
    metadata:
      labels:
        app: wasp-dev-db
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
      containers:
        - resources: {}
          name: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: postgresWaspDevPass
            - name: POSTGRES_USER
              value: postgresWaspDevUser
            - name: POSTGRES_DB
              value: OpenSaaS-06def77781
          ports:
            - containerPort: 5432
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          terminationMessagePolicy: File
          image: 'postgres:latest'
      securityContext:
        runAsUser: 0
---
kind: Service
apiVersion: v1
metadata:
  name: wasp-dev-db-opensaas-06def77781
  namespace: my-super-saas
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: wasp-dev-db
